version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run: |
          export NG_CLI_ANALYTICS=ci
          npm install @angular/cli	
          npx ng new ng-size-tracking --interactive=false	
          cd ng-size-tracking
          npx ng build --prod
          for file in dist/ng-size-tracking/*.*; do gzip -k $file; done
          ls -lG dist/ng-size-tracking | awk '{ total += $4; print }; END { print total }'

workflows:
  version: 2
  pipeline:
    jobs:
      - build
